apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-nfs-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: true
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  archiveOnDelete: "false"
  pathPattern: "${.PVC.annotations.nfs.io/storage-path}"
  onDelete: retain
mountOptions:
- hard
- noatime
- timeo=600
- retry=5
- actimeo=3
- nodiratime
- intr
