apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-nfs-storage-default
  annotations:
    storageclass.kubernetes.io/is-default-class: true
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  archiveOnDelete: "false"
  pathPattern: "data01/default/${.PVC.name}"
  onDelete: delete
mountOptions:
- hard
- noatime
- timeo=600
- retry=5
- actimeo=3
- nodiratime
- intr
